### PR TITLE
Big refactor, API incompatible changes

### PR DESCRIPTION
**Pull request by abraithwaite**
Hey @jedbrown, we've been using `git-fat` at our company and we love it!

We've made a load of changes to suit our needs and some of those changes make it incompatible with yours.

I've also packaged it as a pypi package to make it easy to install (although it has no real usefulness as a module alone).

I don't expect you to merge it because of the API changes, but we wanted to let you know that we love what you've done and to give back what changes we made.

### CODE REVIEW

**Comment by mattions** [comment]
I see there was a release on PyPi all the way to `0.5.0` (https://github.com/cyaninc/git-fat/commit/a25555b1204db2a443542f1f825f4e3fc349ea01) and the network activity on this package is quite active.

There is a plan to consolidate and bring all the cool stuff into the fold with the blessing of @jedbrown or you guys have different plans?

Best and thanks for this neat module

**Comment by abraithwaite** [comment]
Hi @mattions I've actually been lacking the time to properly maintain the cyaninc fork unfortunately.  I'm not sure what would have been needed to get it back into the mainline here, but I think it'll probably just sit the way it is.

**Comment by ahmadia** [comment]
At this point, the projects have diverged enough that it doesn't really make sense for them to keep using the same name.  @jedbrown - What do you think?

**Comment by jedbrown** [comment]
@ahmadia It appears that neither @abraithwaite nor myself have time to integrate the two forks in the near future. In that case, I think it's important to communicate to users that the two forks are not compatible. Names are the most common way to do that, but at this point would require a name change that may be even more confusing to users, thus I don't have a strong preference.

**Pull request closed without merging**
